/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HandleTidRouteImport } from './routes/$handle.$tid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleTidRoute = HandleTidRouteImport.update({
  id: '/$handle/$tid',
  path: '/$handle/$tid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$handle/$tid': typeof HandleTidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$handle/$tid': typeof HandleTidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$handle/$tid': typeof HandleTidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$handle/$tid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$handle/$tid'
  id: '__root__' | '/' | '/$handle/$tid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandleTidRoute: typeof HandleTidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle/$tid': {
      id: '/$handle/$tid'
      path: '/$handle/$tid'
      fullPath: '/$handle/$tid'
      preLoaderRoute: typeof HandleTidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandleTidRoute: HandleTidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
